### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by lars-sh** [sabre-io/vobject#387]
Sorry for the request, but might you finish another minor release in the near future? I know, not that much changed since December 2016, but Request #384 fixes an ugly bug in ownCloud and Nextcloud (https://github.com/nextcloud/contacts/issues/206) and some of us'd like to see that fix being applied there, too. Thanks and much appreciation.

**Comment by staabm** [comment]
In case you PR a proper changelog I might find time to merge and tag something
