### ISSUE TITLE
Better handling when unknown TimeZone Identifier encountered in `TZID` property

### ISSUE THREAD

**Issue by jpirkey** [sabre-io/vobject#393]
# Question:
I think it makes sense to use the passed in timezone if we can not parse the timezone identified in `TZID` instead of falling back to `UTC`.  Is there a reason why we don't do that? Otherwise we aren't truly falling back to the timezone we specified.

# Current code:
https://github.com/sabre-io/vobject/blob/77539407b7f31ace904ea2484331b2751d8672b9/lib/Property/ICalendar/DateTime.php#L175

which will return `UTC` if it can't determine the time zone.

# Code change suggested:
```php
         try {
              $parsedTimeZone = TimeZoneUtil::getTimeZone((string)$tzid, $this->root, true);
              $timeZone = $parsedTimeZone;
          }
          catch (\InvalidArgumentException $e) {
              // use the passed in timeZone if one is specified
          }
```

Thoughts?

**Comment by evert** [comment]
The timeZone argument has a very specific purpose, and that's to handle floating dates/times (an important iCalendar concept). This feature should not be overloaded to handle unrecognized timezones. In most cases that argument should not be specified at all. There's only a few, very specific contexts where this should be done.

Aside from that, I think `UTC` is a much stronger indicator 'something went wrong' than allowing a consumer of the api to specify some default.

**Comment by jpirkey** [comment]
Fair enough.  Thanks for taking the time to response.
