### ISSUE TITLE
Issue is with PHP Version 5.6.33

### ISSUE THREAD

**Issue by rameshsrinivasan** [sabre-io/vobject#420]
Hi,

My Server is running PHP Version 5.6.33, and I can not upgrade to next version. This plugin is not supporting on this version. Please help me to sort out this.
Thanks in advance.

**Comment by DeepDiver1975** [comment]
Which version are you using?
How did you install this library?

Generally speaking:
Option A: Update php
Option B: stay on your current major version

**Comment by DeepDiver1975** [comment]
4.1 is supporting php 5.5 and higher - see https://github.com/sabre-io/vobject/blob/8899c0e856b3178b17f4e9a4e85010209f32a2fa/composer.json#L33

No idea what error you are experiancing

**Comment by rameshsrinivasan** [comment]
@DeepDiver1975 Latest PHP version it is working fine. But PHP version with 5.6 its getting error.
vobject\vendor\sabre\uri\lib\functions.php
Issue is with declare (strict_types=1);
This issue is reproducible only on PHP Version 5.6 only.

**Comment by DeepDiver1975** [comment]
> vobject\vendor\sabre\uri\lib\functions.php

this is the lib sabre/uri - looks like the wrong version of that library has been pulled into your system

**Comment by DeepDiver1975** [comment]
you need to grab the correct verion: see https://github.com/sabre-io/uri/tree/master#build-status

**Comment by rameshsrinivasan** [comment]
After changing this version, Now it is working fine. You saved my time.
Thanks @DeepDiver1975
