### ISSUE TITLE
Never reoccurring recurrence loops forever

### ISSUE THREAD

**Issue by brianmuse** [sabre-io/vobject#442]
Consider this recurrence rule:

`RRULE:FREQ=MONTHLY;BYDAY=2TU;BYSETPOS=2`

Systems like google accept this as a valid rule, but it never reoccurs... There is only one "second Tuesday" in each month. Putting this into a Google event results in a recurring event that occurs on the first date and never again.

The `RRuleIterator` becomes stuck in the `while(true)` loop, looping until the year `9999` to try to find the next occurrence and finally breaking when it hits the year `10000` and the `DateTimeImmutable` constructor fails.

**Comment by DeepDiver1975** [comment]
here is the fix: https://github.com/sabre-io/vobject/pull/443
