### ISSUE TITLE
precedence of the concatenation operator 

### ISSUE THREAD

**Issue by staabm** [sabre-io/vobject#451]
according to the source analysis of Nikita Popov on, we might face some bugs in our implementation.

https://externals.io/message/104980#105442

findings: https://gist.github.com/nikic/a4df3e8e18c7955c2c21cf6cdb4cbfaa

```
(BUG!) /home/nikic/package-analysis/sources/sabre/vobject/lib/Recur/RRuleIterator.php:344

$this->currentDate = $this->currentDate->modify('+'.$this->interval - 1 .' days');

(BUG!) /home/nikic/package-analysis/sources/sabre/vobject/lib/Recur/RRuleIterator.php:404

$this->currentDate = $this->currentDate->modify('+'.$this->interval - 1 .' weeks');
```

we should check whether we need to fix something

**Comment by staabm** [comment]
atm I dont have time to investigate this further, just want to let this information here in case someone else can have a look at it.

**Comment by evert** [comment]
Surprised that this would have worked then :/

**Comment by DeepDiver1975** [comment]
This is not an issue as of today. This is in the context of an RFC for a future version of PHP: https://wiki.php.net/rfc/concatenation_precedence

So not much to worry now .... as soon as this RFC is getting accepted and we start to support that new php version then, then there is action required.

**Comment by DeepDiver1975** [comment]
The RFC is targetting php8 ....  if there are no objections I vote to close this.
Once we migrate to php8 we will take care of this.

never the less @staabm THX for the hint!

**Comment by PHPGangsta** [comment]
I'm not sure, but the code currently has a bug?! Why not fix that bug?

Please see the introduction again of the RFC:
```
// current behavior: evaluated left-to-right
echo ("sum: " . $a) + $b;
// desired behavior: addition and subtraction have a higher precendence
echo "sum :" . ($a + $b);
```

In VObject there is this code:
`modify('+'.$this->interval - 1 .' days')`

In current PHP versions, "." is stronger than "-". But your intention of the code is:

`modify('+' . ($this->interval - 1) . ' days')`

which would be the new behaviour if the RFC is accepted. Or am I wrong?

As far as I understand it, it's a bug now, and should be fixed.

**Comment by PHPGangsta** [comment]
Without brackets:
`php -r '$number = 3; echo "+".$number - 1 ." days";'`
results in: `2 days`

With brackets:
`php -r '$number = 3; echo "+".($number - 1) ." days";'`
results in: `+2 days`

The "+" is missing in the output.
It's definitly a bug. It just works "by accident" currently.

**Comment by DeepDiver1975** [comment]
@PHPGangsta you are absolutly right - by accident this works ...
$date->modify('+2 days')
is identical to
$date->modify('2 days')

**Comment by staabm** [comment]
@DeepDiver1975 thx for taking care of it.

**Comment by PHPGangsta** [comment]
Thx @DeepDiver1975
