### ISSUE TITLE
EXDATE not working with OS X Calendar

### ISSUE THREAD

**Issue by rico** [sabre-io/vobject#454]
I'm looking for advice on how to add `EXDATE` properties that are understood by OS X Calendar - and other clients.

If I add `EXDATE` in the normal way, they are serialised to: 

    EXDATE:20190527T000000Z,20190708T000000Z

which seems to be right when I look it up in the RFC.

However, the OS X Calendar app does not _recognize_  this format.  The excluded dates are still shown in the calendar.

So, I created an example event in the Calendar app and removed a few dates. The `EXDATE` properties then look like:

    EXDATE;TZID=Europe/Zurich:20190527T090000
    EXDATE;TZID=Europe/Zurich:20190708T090000

Is it possible to use vobject to add the excluded dates in such a format - even without getting validation errors?

Is it kind of an alternative format that is also readable by other clients?

Thanks for you advice ...

**Comment by evert** [comment]
Times with timezones and utc times are very different things, even if today two things would be considered the same, timezone rules changes all the time.

Therefore recurring events and exceptions must all appear in the same time+timezone as the intended local time.

All your examples are valid EXDATE properties but it sounds like your event had a DTSTART in Europe/Zurich and your EXDATE needs to match exactly that

**Comment by rico** [comment]
Good to know. Timezones are not important for my use case. So I omit the timezone info from `DTSTART` and `DTEND`.

However, `EXDATE` was not working in the Calendar app until I set the time part of the excluded  dates (datetimes) to the same start time as the event. So in my case for a weekly event:

Event start:

    DTSTART:20190513T183000Z
    RRULE:FREQ=WEEKLY

Excluded dates:

    EXDATE:20190527T183000Z,20190708T183000Z

@evert thank you for your time - again!
