### ISSUE TITLE
Upcoming Events with Sorting and Reference to Original Event

### ISSUE THREAD

**Issue by rico** [sabre-io/vobject#455]
What I need is a list of upcoming events, sorted ascending by start date, calculated from a collection of events (`VCalendar` objects), which may be single or recurring.

I found the free-busy report (`VFreeBusy->getResult`) quite useful to calculate the periods and get the sorting right. Unfortunately I can not figure out to which original event the calculated period corresponds to.

Is also tried to _merge_ multiple events (`vCalendar` objects) into one `vCalendar` object - as I can easily add custom properties to an extended `VCalendar` class and therefore track the event  -  and use the `VCalendar->expand` method. This works, but then the sorting is not correct - sure, could order them manually afterwards.

So, is there any way to get the event data in `VFreeBusy->getResult` or the sorting in the `VCalendar->expand` method? 

Any other approaches or suggestions?

**Comment by evert** [comment]
The right approach would be to use `->expand` and just to sort the result with PHP's usort() function.

**Comment by rico** [comment]
Thanks @evert.
