### ISSUE TITLE
Undefined index: plusminus

### ISSUE THREAD

**Issue by mschering** [sabre-io/vobject#467]
I encountered an Invite from exchange server that contains this:

BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:P
ACTION:DISPLAY
END:VALARM

It has a strange trigger value. This gives the following error in sabre/vobject:

feedback": "Undefined index: plusminus",
    "exceptionCode": 0,
    "exceptionClass": "ErrorException",
    "trace": [
        "#0 /usr/local/share/src/www/vendor/sabre/vobject/lib/DateTimeParser.php(107): go\\core\\ErrorHandler::errorHandler(8, 'Undefined index...', '/usr/local/shar...', 107, Array)",
        "#1 /usr/local/share/src/www/vendor/sabre/vobject/lib/Component/VAlarm.php(32): Sabre\\VObject\\DateTimeParser::parseDuration(Object(Sabre\\VObject\\Property\\ICalendar\\Duration))",
        "#2 /usr/local/share/src/www/modules/calendar/model/Event.php(1871): Sabre\\VObject\\Component\\VAlarm->getEffectiveTriggerTime()",

Perhaps this can be ignored?

**Comment by phil-davis** [comment]
Fixed by PR #619 - it will be in the next release.
