### ISSUE TITLE
PHP module dependencies

### ISSUE THREAD

**Issue by tcdaly** [sabre-io/vobject#475]
Installation with composer keeps failing due to missing PHP modules.  Is there a list of SabreDav's PHP module dependencies?

**Comment by evert** [comment]
Yes it's in composer.json ;)

**Comment by tcdaly** [comment]
Thanks.  Would be useful if this was added to http://sabre.io/dav/install/ under 'Requirements'.

**Comment by DeepDiver1975** [comment]
Documentation always lies.
Code comments are sometimes right.
Only the code holds the truth.
🤪🤪

**Comment by DeepDiver1975** [comment]
As Developer it is quite common to read/Work with composer. No additional docs are required

**Comment by staabm** [comment]
We could link to the composer.json from the docs and mention that all ext requirements are documented in there
