### ISSUE TITLE
Release needed for PHP 7.4 fix

### ISSUE THREAD

**Issue by phil-davis** [sabre-io/vobject#478]
Now that PHP 7.4 has been officially released, I am noticing the PHP deprecated notices in ownCloud CI:
```
[PHP Deprecated:  The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /drone/src/lib/composer/sabre/vobject/lib/Recur/RRuleIterator.php on line 341]
[PHP Deprecated:  The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /drone/src/lib/composer/sabre/vobject/lib/Recur/RRuleIterator.php on line 401]
```
This was corrected in issue #451 and PR #452 

Maybe it is time to make a release `4.2.1` or `4.30` (whatever is appropriate given the other things that are also in master since `4.2.0` )

@staabm @DeepDiver1975 ?

**Comment by phil-davis** [comment]
Lots of thumbs-up. Who can actually do the release?
@staabm @DeepDiver1975

**Comment by staabm** [comment]
Didn‘t had time the last few days.. hopefully sometime this week
