### ISSUE TITLE
Release 4.3.1

### ISSUE THREAD

**Issue by phil-davis** [sabre-io/vobject#509]
Since release 4.3.0 there have been lots of refactorings of CI stuff, but nothing interesting in the code.

Today PR #505 was merged. It adjusts some unit test code. `sabre/dav` runs the unit tests out of `vobject` (as well as other unit tests of its own). So to keep `sabre/dav` happy it needs "access" to the latest `vobject` unit tests.

I  think a release is needed to make it so. @staabm ?

**Comment by staabm** [comment]
> So to keep sabre/dav happy it needs "access" to the latest vobject unit tests.

I dont know whether this true. Did you verify the sabre/dav is missing latest tests?

**Comment by phil-davis** [comment]
https://travis-ci.org/github/sabre-io/dav/jobs/701503794
https://github.com/sabre-io/dav/pull/1278
The unit test CI in `sabre/dav` is just getting the current release of `sabre/vobject` and the unit test code that comes with that.
So a `sabre/vobject`  release will get rid of the the unit test warning in `sabre/dav`

Note: I thought that CI actually failed in `sabre/dav` because of this, but somehow the unit tests emit a warning but do not fail the CI pipeline.

**Comment by staabm** [comment]
I see. Can you take care of creating a new release?

**Comment by phil-davis** [comment]
I will do "later" (tm) - assigned myself. But if I come back and the release is already done, then I will not complain ;) @staabm

**Comment by phil-davis** [comment]
https://github.com/sabre-io/vobject/releases/tag/4.3.1
