### ISSUE TITLE
Reordering of the attendees should not be a signitifcant change

### ISSUE THREAD

**Issue by floerke** [sabre-io/vobject#540]
If a server (using sabre) receives a VEVENT update it will send mails to all attendees. Not for all modified events, but for events with a "significant change". The calculation of "signifcant change" is done by vobject. 

I have trouble with to many "Invitation: ..."-Mails for events that has not been changed. 

Investigating this I have seen:
- the events were modified by the client and sent to the server (eg. to save the acknowledgment of an alarm).
- the client has changed the order (not the attendees itself) of the attendees in the modified event
- vobject calculated a "significant change"
- the server sent the email

I think everything is correct, except, the reordering is not a significant change. Why the client desires to reorder the attendees? I don't know, but I think this should not be a significant change.

**Comment by phil-davis** [comment]
Fixed by #541
