### ISSUE TITLE
Help with Fatal error createProperty

### ISSUE THREAD

**Issue by ravivgolov** [sabre-io/vobject#569]
Hi
I am using calendar plugin for RoundCube Webmail, any time i am trying to create an event, I receive the following error:
`[12-Apr-2022 17:56:08 UTC] PHP Fatal error:  Uncaught TypeError: Sabre\VObject\Document::createProperty(): Argument #3 ($parameters) must be of type array, null given, called in /var/www/html/plugins/libcalendaring/libvcalendar.php on line 939 and defined in /usr/share/php/Sabre/VObject/Document.php:103`

The functions:
`public function createProperty($name, $value = null, array $parameters = null, $valueType = null)
    {
        // If there's a . in the name, it means it's prefixed by a groupname.
        if (false !== ($i = strpos($name, '.'))) {
            $group = substr($name, 0, $i);
            $name = strtoupper(substr($name, $i + 1));
        } else {
            $name = strtoupper($name);
            $group = null;
        }

        $class = null;

        if ($valueType) {
            // The valueType argument comes first to figure out the correct
            // class.
            $class = $this->getClassNameForPropertyValue($valueType);
        }

        if (is_null($class)) {
            // If a VALUE parameter is supplied, we should use that.
            if (isset($parameters['VALUE'])) {
                $class = $this->getClassNameForPropertyValue($parameters['VALUE']);
                if (is_null($class)) {
                    throw new InvalidDataException('Unsupported VALUE parameter for '.$name.' property. You supplied "'.$parameters['VALUE'].'"');
                }
            } else {
                $class = $this->getClassNameForPropertyName($name);
            }
        }
        if (is_null($parameters)) {
            $parameters = [];
        }

        return new $class($this, $name, $value, $parameters, $group);
    }`

Call it:
`$vdt = $cal->createProperty($name, $dt, null, $is_dateonly ? 'DATE' : 'DATE-TIME');`

Does anyone know how to fix this?

**Comment by DeepDiver1975** [comment]
This method is called by plugins/libcalendaring/libvcalendar.php which is from roundcube (?) - you better reach out to them why they call this method with null instead of an array - as the method signature states ....
