### ISSUE TITLE
getNormalizedValue() should lowercase emailaddresses

### ISSUE THREAD

**Issue by pk1234** [sabre-io/vobject#572]
There's bug sabre-io/dav#1250 which can be fixed by changing getNormalizedValue() from sabre-io/vobject.

I have already created pull-request #565 which has not been reviewed so far.

Is there anything else I can do?

Peter

**Comment by kesselb** [comment]
Hey, I guess this is resolved?

**Comment by staabm** [comment]
correct. thx
