### ISSUE TITLE
vobject 4.5 requires sabre xml 2.1

### ISSUE THREAD

**Issue by mstilkerich** [sabre-io/vobject#584]
Hello, the new release does not allow combination with the also newly released sabre xml 3. I guess this is not intended.

**Comment by phil-davis** [comment]
I tried in #585 but the code is not quite ready yet in `sabre/vobject` - see my comment https://github.com/sabre-io/vobject/pull/585#issuecomment-1218945269

Also see #562 - I plan to grab that, rebase it, and get it ready today. That will get the type declarations etc all up-to-date.

**Comment by mstilkerich** [comment]
Intended after all then! Thanks for the information.

**Comment by phil-davis** [comment]
> Intended after all then! Thanks for the information.

not so much "intended" as "didn't think hard about it or try it" and it turned out anyway that we need to wait!
