### ISSUE TITLE
parser error when DATE is empty

### ISSUE THREAD

**Issue by JohnRDOrazio** [sabre-io/vobject#646]
I was attempting to parse a defective ICS file, which happened to have empty `CREATED:` and `LAST-MODIFIED:` fields:
```ical
BEGIN:VEVENT
CLASS:PUBLIC
DTSTART;VALUE=DATE:20291231
DTSTAMP:20240422T062620Z
UID:c0e7126a841a70761e4057e58b5e2d52
CREATED:
DESCRIPTION:\nA fun event\nRSVP
LAST-MODIFIED:
```

I wasn't getting parsing errors from the `validate()` call, instead I was getting PHP warnings about an uninitialized string offset 0 in the `DateTimeParser::parse()` method, specifically from the line:
```php
if ('P' === $date[0] || ('-' === $date[0] && 'P' === $date[1])) {
```

The PHP warning made me realize that `$date` was empty, and in fact upon inspecting the ICS file I found the empty `CREATED:` and `LAST-MODIFIED:` fields.

Perhaps the parser should catch those situations in which the expected field has an empty value, and throw a catchable error?

https://github.com/sabre-io/vobject/blob/caa7af8e3304c85c63cdb6464ecafe09bb9918f6/lib/DateTimeParser.php#L202-L211

**Comment by phil-davis** [comment]
@JohnRDOrazio can you propose some code, and add a unit test, in a PR.
Then I can review it.

It will be good to handle defective input data, rather than just have PHP "crash".

**Comment by JohnRDOrazio** [comment]
I'm seeing that `MimeDir` does actually keep track of the line index when reading and parsing a file:

https://github.com/sabre-io/vobject/blob/caa7af8e3304c85c63cdb6464ecafe09bb9918f6/lib/Parser/MimeDir.php#L289

https://github.com/sabre-io/vobject/blob/caa7af8e3304c85c63cdb6464ecafe09bb9918f6/lib/Parser/MimeDir.php#L296-L298

Perhaps the `Property` class could have an extra property `public int $lineIndex;` which could be set when creating a new Property? That way each node could keep track of it's own line number within the original file?

**Comment by JohnRDOrazio** [comment]
ok so this is a little bit strange... I've tried adding `$lineIndex` and `$lineString` public properties to the `Property` class:
```php
    public function __construct(Component $root, $name, $value = null, array $parameters = [], $group = null, $lineIndex = null, $lineString = null)
    {
        $this->name = $name;
        $this->group = $group;

        $this->root = $root;

        foreach ($parameters as $k => $v) {
            $this->add($k, $v);
        }

        if (!is_null($value)) {
            $this->setValue($value);
        }

        if (!is_null($lineIndex)) {
            $this->lineIndex = $lineIndex;
        }

        if (!is_null($lineString)) {
            $this->lineString = $lineString;
        }
```

and I added them to the `Document->createProperty` method:
```php
    public function createProperty($name, $value = null, array $parameters = null, $valueType = null, $lineIndex = null, $lineString = null)
    {
      //...
      return new $class($this, $name, $value, $parameters, $group, $lineIndex, $lineString);
    }
```

and I set them inside `MimeDir->readProperty( $line )` when the `Property` is created:
```php
$propObj = $this->root->createProperty($property['name'], null, $namedParameters, $this->lineIndex, $line);
```

However, when checking `node->lineIndex` in the errors gathered from the `validate()` method, it's giving me the property name? I'm seeing `LAST-MODIFIED:` and `CREATED:` instead of the line number. At what point can `$this->lineIndex` change from an integer to the property name?

In my test I'm building an error string like this (I created an `ICSErrorLevel` class to get **Warning** or **Fatal Error** strings from the error level):
```php
        $errors = $vcalendar->validate();
        if( count( $errors ) > 0 ) {

            foreach( $errors as $error ) {
                $errorLevel = new ICSErrorLevel( $error['level'] );
                $nodeType = get_class($error["node"]);
                $nodeValue = $error["node"]->getValue();
                $response->errors[] = $errorLevel . ": " . $error['message'] . " at line {$error["node"]->lineIndex} ({$error["node"]->lineString})";// . "($nodeType)";
            }
        } else {
            $response->messages[] = "No validation errors were found while validating data from the defective calendar";
        }
```
and this is from the output:
```console
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line LAST-MODIFIED: ()",
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line CREATED: ()",
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line LAST-MODIFIED: ()",
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line CREATED: ()",
```

There seems to be no value for `$error["node"]->lineString`, while `$error["node"]->lineIndex` is giving the property name?

**Comment by JohnRDOrazio** [comment]
started a fix for this in PR #649

**Comment by JohnRDOrazio** [comment]
with this fix in place I'm able to gather the line number and string from the node passed in the errors, after calling `validate()`:

```php
        $errors = $vcalendar->validate();
        if( count( $errors ) > 0 ) {

            foreach( $errors as $error ) {
                $errorLevel = new ICSErrorLevel( $error['level'] );
                $nodeType = get_class($error["node"]);
                $nodeValue = $error["node"]->getValue();
                $response->errors[] = $errorLevel . ": " . $error['message'] . " at line {$error["node"]->lineIndex} ({$error["node"]->lineString})";// . "($nodeType)";
            }
        } else {
            $response->messages[] = "No validation errors were found while validating data from the defective calendar";
        }
echo json_encode( $response, JSON_PRETTY_PRINT );
```

I can now see in the output:
```console
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line 9277 (LAST-MODIFIED:)",
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line 9292 (CREATED:)",
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line 9294 (LAST-MODIFIED:)",
        "Fatal Error: The supplied value () is not a correct DATE-TIME at line 9309 (CREATED:)",
```
which is quite helpful for identifying the issues quickly and to the point. So instead of doing a `json_encode($errors)` which results in trying to stringify a defective node (and generating a PHP warning), I can better examine the node in question and see exactly where it is located in the original file.

**Comment by JohnRDOrazio** [comment]
I added a unit test to the PR which verifies that `lineIndex` and `lineString` parameters are accessible on the `node` reference in the errors returned from a `validation()` on defective calendar data.

**Comment by phil-davis** [comment]
Released in https://github.com/sabre-io/vobject/releases/tag/4.5.5
