### ISSUE TITLE
Parse an iCal calendar, how to get all events?

### ISSUE THREAD

**Issue by laptop-doug** [sabre-io/vobject#650]
I tried the 'basic parsing example' from the docs.  also tried `->children()`.  
` $vcalendar->VEVENT` gave me one basically empty array. ` Children()` gave me a bigger array, but no events.

I have verified that the proper string, from the ical is getting to the 
`$vcalendar = VObject\Reader::read($icalData);`

**Comment by gharlan** [comment]
`foreach ($vcalendar->VEVENT as $vevent) { ... }`

**Comment by laptop-doug** [comment]
got it, thank you.
