### ISSUE TITLE
VTODO PERCENT-COMPLETE property is not validated correctly

### ISSUE THREAD

**Issue by jarikmarwede** [sabre-io/vobject#663]
According to [RFC 5545](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.1.8) the property to convey the percent completion of a to-do is called `PERCENT-COMPLETE`. 
However, in [`VTodo.php`](https://github.com/sabre-io/vobject/blob/1b388aab5cdbcb75a09be25f2e9119fc4463ae59/lib/Component/VTodo.php#L107) in the validation rules it checks for just `PERCENT`. This means that, for example, this VTODO does not trigger any errors when analyzed by the `validate` method, even though the `PERCENT-COMPLETE` property occurs two times which is invalid according to the standard.
```
BEGIN:VTODO
UID:8ed267e1-67c4-467d-8ae2-28e6ff03b033
DTSTAMP:20240729T133309Z
SUMMARY:TestTitle
COMPLETED;TZID=Europe/Berlin:20240729T133314
STATUS:COMPLETED
PERCENT-COMPLETE:70
PERCENT-COMPLETE:80
END:VTODO
```

Why is the library checking for `PERCENT`? Am I missing something?

**Comment by phil-davis** [comment]
My guess is an accident because of
https://www.rfc-editor.org/rfc/rfc5545#section-3.6.2
```
; The following are OPTIONAL,
; but MUST NOT occur more than once.
;
class / completed / created / description /
dtstart / geo / last-mod / location / organizer /
percent / priority / recurid / seq / status /
summary / url /
```
The Format Definition has "percent", and then "percent" is defined as:
```
Format Definition:  This property is defined by the following notation:
       percent = "PERCENT-COMPLETE" pctparam ":" integer CRLF
```
And that results in the actual property being called `PERCENT-COMPLETE`

@staabm @evert do you have any memory of this? Is it just an accident that needs to be fixed?

**Comment by staabm** [comment]
I have no idea

**Comment by jarikmarwede** [comment]
> My guess is an accident because of https://www.rfc-editor.org/rfc/rfc5545#section-3.6.2
> 
> ```
> ; The following are OPTIONAL,
> ; but MUST NOT occur more than once.
> ;
> class / completed / created / description /
> dtstart / geo / last-mod / location / organizer /
> percent / priority / recurid / seq / status /
> summary / url /
> ```
> 
> The Format Definition has "percent", and then "percent" is defined as:
> 
> ```
> Format Definition:  This property is defined by the following notation:
>        percent = "PERCENT-COMPLETE" pctparam ":" integer CRLF
> ```
> 
> And that results in the actual property being called `PERCENT-COMPLETE` - but maybe someone "accidentally" implemented the property called `PERCENT`
> 
> @staabm @evert do you have any memory of this? Is it just an accident that needs to be fixed?

That seems likely. The RFC is definitely a bit hard to read.

In case nobody finds a valid use case for the `PERCENT` property, I have created a PR to fix the property. #664

**Comment by evert** [comment]
late to the party but the assumption I mistyped this seems highly likely!
